# fly.toml app configuration file generated for holy-field-1850 on 2023-06-02T14:34:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-field-1850"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
